apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-redis-replica
spec:
  serviceName: svc-redis-internal
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis
          image: redis:7.2
          command:
          - redis-server
          - /etc/redis/redis.conf
          - --masterauth
          - $(REDIS_PASSWORD)
          - --requirepass
          - $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-redis
                key: redis_password
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
      volumes:
        - name: config
          configMap:
            name: cm-redis-replica
        - name: redis-data
          persistentVolumeClaim:
            claimName: pvc-redis-replica
