apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-redis-node
spec:
  serviceName: svc-redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          command:
          - redis-server
          - /etc/redis/redis.conf
          - --masterauth
          - $(REDIS_PASSWORD)
          - --requirepass
          - $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 1Gi
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-redis-cluster
                key: redis_password
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
      volumes:
        - name: config
          configMap:
            name: cm-redis-cluster
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 3Gi
