apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-redis-replica
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    appendonly yes
    dir /data
    replicaof sts-redis-master-0.svc-redis-master 6379