apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-redis-replica
data:
  redis.conf: |
    save 900 1
    save 300 10
    appendonly yes
    appendfsync everysec
    dir /data
    replicaof sts-redis-master-0.svc-redis-master 6379