apiVersion: v1
kind: Service
metadata:
  name: svc-redis-master
spec:
  clusterIP: None
  selector:
    app: redis
    role: master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-redis-master
spec:
  serviceName: svc-redis-master
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:7.2
          args:
          - /etc/redis/redis.conf
          - --requirepass
          - $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 200m
              memory: 3Gi
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-redis
                key: redis_password
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
      volumes:
        - name: config
          configMap:
            name: cm-redis-master
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
