apiVersion: v1
kind: Service
metadata:
  name: svc-redis
spec:
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-redis
spec:
  serviceName: svc-redis
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:7.2
          command:
          - sh
          - -c
          args:
          - |
            cp /tmp/redis.conf /etc/redis/redis.conf
            redis-server /etc/redis/redis.conf \
              --masterauth $(REDIS_PASSWORD) \
              --requirepass $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 3Gi
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-redis
                key: redis_password
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: config
              mountPath: /tmp
            - name: etc-redis
              mountPath: /etc/redis
      volumes:
        - name: config
          configMap:
            name: cm-redis
        - name: etc-redis
          emptyDir: {}
    
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 5Gi
