apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-redis-sentinel
data:
  sentinel.conf: |
    sentinel resolve-hostnames yes
    sentinel monitor mymaster sts-redis-0.svc-redis 6379 2
    sentinel down-after-milliseconds mymaster 2000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000